version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: murpheus-portfolio
    image: murpheus-portfolio
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - social-downloader_streambolt-net

networks:
  social-downloader_streambolt-net:
    external: true
